import * as momentTZ from 'moment-timezone';
import { faker } from '..';
export const payload = {
    locoid: "CC202-11-11",
    gpsdatetime: momentTZ.tz('Asia/jakarta').format('YYYY-MM-DD HH:mm:ss'),
    longitude: faker.faker.address.longitude(112, 100, 5),
    latitude: faker.faker.address.longitude(1, -0.1, 5),
    speed: faker.faker.datatype.float({min: 0, max:100, precision: 0.001 }),
    heading: faker.faker.datatype.float({min: 0, max:100, precision: 0.001 }),
    tekmp: faker.faker.datatype.float({min: 0, max:100, precision: 0.001 }),
    tekap: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tekt: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tekcc: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tekbp: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tekbc: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tekmr: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tpse: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tpsete: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tpdsr: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tpdser: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    tengroom: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    fuel: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    voltmg: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm1: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm2: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm3: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm4: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm5: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    currtm6: faker.faker.datatype.float({ min:0 , max:100, precision: 0.001 }),
    rpm: faker.faker.datatype.number({min: 1000, max: 100000, precision: 100 }),
    throttle: faker.faker.datatype.number({ min:1, max: 8, precision: 1 }),
    reverser: "FOR",
    network: "TSEL 2G/3G/4G",
    sigquality: faker.faker.datatype.number({min: 1, max: 5, precision: 1})
}